### ISSUE TITLE
_watchdog() can set many timers

### ISSUE THREAD

**Issue by philmy** [electricimp/Bullwinkle#10]
It would be good to move [this call](https://github.com/electricimp/Bullwinkle/blob/v2.2.0/Bullwinkle.class.nut#L430) out of the foreach loop, since agent timers are a limited resource. Maybe build a list of onFail handlers and have the async function reschedule itself while the list is not empty.

**Comment by betzrhodes** [comment]
removed imp.wakeup(0) from the loop in _watchdog.  this fix will go live when v2.2.1 is released.

**Comment by betzrhodes** [comment]
v2.2.1 is now live
