### ISSUE TITLE
Defend against low memory situations

### ISSUE THREAD

**Issue by deldrid1** [electricimp/Bullwinkle#18]
If a partner Agent, gets hung up in a long running synchronous task, then Bullwinkle responses will not be sent in a timely manner.  Assuming you are sending data regularly from a Device, keeping large Bullwinkle messages around in RAM can chew through memory pretty quickly.

Whenever `Bullwinkle.send()` (or `retry`) is called, it should check the memory situation with `imp.getmemoryfree()`.  If the value is below a configurable threshold (default to 10000?), then the .onFail handler should be called immediately so that the object can be handled by the programmer (discarded, written to spiflash, etc.) and not cause the device to crash...

I am trying to achieve data resiliency - essentially by combining Bullwinkle and some of the SPIFlash libraries, I would like to ensure that any data generated on the device, is reasonably assured that it will make it up to the Agent and eventually 3rd party systems.  Crashing and losing objects in RAM doesn't make this very easy :).  While I could do the checks outside of Bullwinkle for imp.getmemoryfree(), it will be a LOT cleaner if implemented in the class.

**Comment by blindman2k** [comment]
The most obvious question to ask is why your agent is doing anything synchronously?

**Comment by deldrid1** [comment]
See https://github.com/deldrid1/big.nut - math on arbitrary precision numbers with my current implementation is expensive unfortunately...

I'm looking at putting together a higher performance UINT64 class (since that is all that I need - arbitrary precision is massive overkill) but that hasn't happened just yet.

**Comment by blindman2k** [comment]
What about checking the queue/memory before you send it? I am loath to add device side code to solve one customers problem that everyone else gets stuck with.

**Comment by deldrid1** [comment]
Maybe presenting the problem a different way makes it more justifiable?

The use case here would be for an imp that regularly sends data who can't communicate with its Agent for whatever reason (internet upstream of the WiFi router has gone down).  Before the imp realizes that it is disconnected (which by the way, Bullwinkle does no checking for - I'm guessing that it waits for timeouts in this situation?  Either way that probably warrants its own issue), it fills up RAM with messages and crashes itself unnecessarily, leading to poor end user experience, as the device obviously won't be functional while it is rebooting.

**Comment by ppetrosh** [comment]
The more I look at the code and think of this, the more it looks to me to be an application level issue. Even if we addess the package/handler registration routines and add the appropriate checks for memory consumption there, we may fail at other libraries and application code.

Does it sound like a right approach to add a handler at the imp level to monitor oom issues, for example:

imp.onoutofmemory(minimumAllowedHeapAvailable, callback)

which will register a callback to be called (not guaranteed, but vm can promise to do it's best:) when the VM identifies that the maximum allowed amount of memory (may be fragmented of course) is not exceeding minimumAllowedHeapAvailable. I'm not sure if it's feasible from the embedded side.

Would it work for the use cases, that you can anticipate, Austin?

Another option would be to have an OOM handler at the Bullwinkle level, which makes much less sense to me.

What do you think?

**Comment by deldrid1** [comment]
An impOS level callback function certainly makes sense for a lot of use cases and could be beneficial.  

For my particular use case however (which is primarily a real-time data logger), I'm still going to want to either build protection into Bullwinkle directly or extend the class for convenience.  If Bullwinkle throughput is where it should be or there isn't anything interesting happening with the device, I sit with ~40kb memory free with my squirrel pushing ~10MB / device / day.  Doing the math (10_1024_1024/86400), this breaks down to ~121 bytes/second, however, some of the event driven data can be quite bursty, generating 10kb+ in 200ms.  These also tend to happen in clusters of events.  As soon as I get down to ~15kb free memory, I want to be writing the "heavy" data to spiflash to trickle up to the agent when the bursty data stops occurring.  Based on my current code architecture, it seems like the obvious place to make this decision is in Bullwinkle...

I'm happy to consider alternatives, this approach just feels philosophically the most correct to me.

**Comment by ppetrosh** [comment]
Thanks for your feedback, Austin. Will the impOS level callback solve your particular use case? Or will you still have to extend the Bullwinkle library to implement the message throttling?

**Comment by deldrid1** [comment]
The impOS level callback would allow me to set a global flag on what to do, but I believe that our preferred implementation would be to override the Bullwinkle class and have it directly call the .onFail handler if imp.getmemoryfree() was below a user definable threshold.   

In this way we can have a single strategy to deal with a message not being successfully sent for whatever the reason may be and not have "special" handling for low memory versus a connectivity issue.  In our particular application low memory is really just a symptom of poor connectivity anyway...

**Comment by ppetrosh** [comment]
Hi Austin. We'll keep track of this issue. If your suggested workaround works for you and we see a demand from other developers/use cases, we'll incorporate this functionality into the core library. Meanwhile we'll consider other options as well. Is it okay with you?

**Comment by ppetrosh** [comment]
My suggestions is to close this issue as it's being addressed by the MessageManager/ReplayMessenger now.
