### ISSUE TITLE
onAck() callback

### ISSUE THREAD

**Issue by blindman2k** [electricimp/Bullwinkle#4]
It seems a waste to have onReply() and onFail() but not onAck() or onSuccess().

**Comment by blindman2k** [comment]
Added onSuccess in [pull request 6](https://github.com/electricimp/Bullwinkle/pull/6) for v2.1.0.

**Comment by betzrhodes** [comment]
Pull request merged. Feature onSuccess() added in release v2.2.0

**Comment by jayeheffernan** [comment]
Issue is resolved
